services:
  # 1. Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: jasfly_db
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jasfly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend de Express
  api:
    build: .
    container_name: jasfly_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    # Ejecuta el seed y luego inicia la API
    entrypoint: /bin/sh -c "node seed.js && npm run dev"

volumes:

  postgres_data:
